# Generated by Django 6.0.6 on 2026-06-21 07:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "currency",
                    models.CharField(
                        choices=[("KZT", "Тенге"), ("USD", "Доллар"), ("EUR", "Евро")],
                        default="KZT",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_name", models.CharField(default="Kaspi PDF", max_length=120)),
                ("file_name", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("added_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                (
                    "raw_file",
                    models.FileField(blank=True, null=True, upload_to="imports/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("person", "Человек"),
                            ("company", "Компания"),
                            ("service", "Сервис"),
                            ("other", "Другое"),
                        ],
                        default="person",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Доход"),
                            ("expense", "Расход"),
                            ("transfer", "Перевод"),
                            ("debt", "Долг"),
                            ("saving", "Накопление"),
                            ("fee", "Комиссия"),
                            ("other", "Другое"),
                        ],
                        default="expense",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("kaspi_pdf", "Kaspi PDF"),
                            ("manual", "Вручную"),
                            ("api", "API"),
                            ("import", "Импорт"),
                        ],
                        default="kaspi_pdf",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Доход"),
                            ("expense", "Расход"),
                            ("transfer_in", "Входящий перевод"),
                            ("transfer_out", "Исходящий перевод"),
                            ("deposit_in", "В депозит"),
                            ("deposit_out", "Из депозита"),
                            ("loan_payment", "Погашение кредита"),
                            ("cash_withdrawal", "Снятие наличных"),
                            ("fee", "Комиссия"),
                            ("adjustment", "Корректировка"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("operation_date", models.DateField(db_index=True)),
                ("operation_time", models.TimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="KZT", max_length=3)),
                ("description", models.CharField(max_length=255)),
                ("raw_description", models.TextField(blank=True)),
                ("operation_type", models.CharField(blank=True, max_length=80)),
                ("direction", models.SmallIntegerField(default=-1)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("note", models.TextField(blank=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("is_split", models.BooleanField(default=False)),
                ("is_void", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="main.account",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="main.importbatch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="main.category",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="main.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-operation_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DebtEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("you_lent", "Ты дал"),
                            ("they_repaid", "Тебе вернули"),
                            ("you_returned", "Ты вернул"),
                            ("they_paid", "Они заплатили"),
                            ("adjustment", "Корректировка"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_entries",
                        to="main.person",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debt_entries",
                        to="main.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTagLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.transactiontag",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["operation_date"], name="main_transa_operati_f79a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["kind"], name="main_transa_kind_88bbc0_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["source"], name="main_transa_source_e5e62b_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["fingerprint"], name="main_transa_fingerp_f4ab0a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactiontaglink",
            unique_together={("transaction", "tag")},
        ),
    ]
